Pytorch

In [1]:
import torch
print(torch.__version__)  # Xem phiên bản PyTorch có sẵn


2.5.1+cu124


In [2]:
import torch

torch.cuda.is_available()

True

Sử dụng GPU và Cuda

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [6]:
# trả về mức sử dụng bộ nhớ gpu hiện taijtheo tensors tính bằng byte cho thiết bị
torch.cuda.memory_allocated()

0

In [7]:
# trả về bộ nhớ gpu hiện tại được quản lý bởi bộ phân bổ bộ nhớ đệm hiện tại
torch.cuda.memory_cached()

<ipython-input-7-107e6c788df7>:2: FutureWarning: `torch.cuda.memory_cached` has been renamed to `torch.cuda.memory_reserved`
  torch.cuda.memory_cached()


0

Dataset with Pytorch

In [10]:
# loading data Iris
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

print(df.head())  # Hiển thị 5 dòng đầu tiên

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [11]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
# xem bao nhiêu hàng nhiu cột
df.shape

(150, 6)

In [17]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(['Id','Species'], axis=1).values
y = le.fit_transform(df['Species'].values)

# chia dữ liệu với test size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)

In [18]:
print(f"train size {len(X_train)}")

train size 120


In [19]:
labels, counts = np.unique(y_train, return_counts=True)
print(labels, counts)

[0 1 2] [40 41 39]


In [ ]:
# Tính đạo hàm bằng pytorch

# Cho y = 2x^4 + x^3 + 3x^2 + 5x +1
# tính y'

import torch

In [20]:
# Tạo một tensor với requirments_grad được đặt thành true

x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [21]:
# định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [22]:
y.grad_fn

In [23]:
# Thực hiện truyền ngược và tính toán các gradient
y.backward()

In [24]:
# Kết quả đạo hàm
print(x.grad)

tensor(93.)


BT
1. Tính y' của y = 5x^6 +3x^3 + 2x^1 +x +2x +5x^4 +1
2. Tìm độ dốc của đa thức trên tại điểm nào


In [26]:
# Tính y' của y = 5x^6 +3x^3 + 2x^1 +x +2x +5^4 +1


# Tìm độ dốc của đa thức trên tại điểm nào


# đáp án x = 1, y =19

tensor(2., requires_grad=True)
None
tensor(980., grad_fn=<AddBackward0>)
tensor(1001.)
Giá trị y tại x = 2.0 là: 980.0
Độ dốc (y') tại x = 2.0 là: 1001.0


BTVN 1:
1. Tạo một tensor x có giá trị ban đầu là 2.0. định nghĩa hàm số:
- Tính gradient
- y = x^3 + 2x^2 +5x +1
- Hãy tính dy/dx tại giá trị của x
- Dùng phương phóa Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng

BTVN 2:
Tạo một tập dữ liệu giả lập với x là số giờ học(ngẫu nhiên từ 1 tới 10) và y là số điểm được tính theo công thức y = 3x +5 + noise
Với noise là một giá trị ngẫu nhiên nhỏ
1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad=True
2. Tính MSE
3. Tính gradient
4. Cập nhật tham số w và b bằng grandient Descent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ mô hình


In [27]:
# pytorch with tensor
import torch
import numpy as np

torch.__version__

'2.5.1+cu124'

In [31]:
# Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [32]:
x = torch.from_numpy(arr)
print(x)
print(x.dtype)
print(type(x))

tensor([1, 2, 3, 4, 5])
torch.int64
<class 'torch.Tensor'>


In [38]:
arr2 = np.arange(0,12).reshape(4,3)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.dtype)
print(x2.type())

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.int64
torch.LongTensor


Copy and sharring

In [40]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)
print(arr)

tensor([0, 1, 2, 3, 4])
[0 1 2 3 4]


In [41]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [ ]:
# BTVN 3:
# Giai thích lý do tại trong 2 trường hợp ở trên một cái dùng a[0] = 99 lại thay đổi mà cái còn lại thì hong?

In [ ]:
# BTVN 4:
# về nahf tạo tensor với empty , zeros, ones, random, reshape với view và view as

Deadline: 15/3